### ISSUE TITLE
Phenotype information is missing for some connectivity paths

### ISSUE THREAD

**Issue by dbrnz** [open-physiology/apinatomy-models#29]
The following have no phenotype:
```
ilxtr:neuron-type-sdcol-k
ilxtr:neuron-type-sdcol-m
ilxtr:neuron-type-sdcol-q-prime
ilxtr:neuron-type-sdcol-i
ilxtr:neuron-type-sdcol-n
ilxtr:neuron-type-sdcol-q
ilxtr:neuron-type-sdcol-p
ilxtr:neuron-type-sstom-2
ilxtr:neuron-type-sstom-11
ilxtr:neuron-type-sstom-13
ilxtr:neuron-type-sstom-3
ilxtr:neuron-type-sstom-14
ilxtr:neuron-type-sstom-4
ilxtr:neuron-type-sstom-12
ilxtr:neuron-type-sstom-6
ilxtr:neuron-type-sstom-1
```

**Comment by dbrnz** [comment]
See also issue #15

**Comment by tgbugs** [comment]
https://github.com/SciCrunch/NIF-Ontology/blob/78403b4895e8bbb47595c3d446c6d0d300382818/ttl/generated/neurons/apinat-pops-more.ttl#L1065

You are likely failing to handle the enteric phenotype object and the hasCircuitRolePhenotype/hasFunctionalCircuitRolePhenotype predicates.

https://github.com/AnatomicMaps/map-knowledge/pull/3 should have resolved the issue

**Comment by dbrnz** [comment]
Thanks.

The list of missing/unknown phenotypes is now down to:
```
ilxtr:neuron-type-sstom-2 phenotype [] is unknown
ilxtr:neuron-type-sstom-11 phenotype ['ILX:0105486'] is unknown
ilxtr:neuron-type-sstom-13 phenotype ['ILX:0105486'] is unknown
ilxtr:neuron-type-sstom-3 phenotype [] is unknown
ilxtr:neuron-type-sstom-14 phenotype ['ILX:0104003'] is unknown
ilxtr:neuron-type-sstom-4 phenotype [] is unknown
ilxtr:neuron-type-sstom-12 phenotype ['ILX:0104003'] is unknown
ilxtr:neuron-type-sstom-6 phenotype [] is unknown
ilxtr:neuron-type-sstom-1 phenotype [] is unknown
```

**Comment by tgbugs** [comment]
Looks like Excitatory and Inhibitory, which means hasFunctionalCircuitRolePhenotype might be missing?

**Comment by tgbugs** [comment]
We think that this issue is mostly resolved with the exception of the 'central nervous phenotype' cases. The hasFunctionalCircuitRolePhenotype issue should be fixed in the anatomical-maps python code if it is not then we should open an issue on that repository.

The issue with those is that we don't want to add an addition defining axiom which would be redundant with the hasSomaLocation axioms, but we also would like to be able to distinguish cases where no additional phenotype information is expected, from cases where it is incorrectly missing.

Given that all neurons currently have the data we expect them to have I am closing this issue, we can open another related to confusion between expected missing and incorrectly missing.
